name: Sauce Cypress Pipeline Demo Tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_USERNAME: ${{secrects.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrects.SAUCE_ACCESS_KEY}}
  SAUCECTL_VERSION: "0.37.0"
  BUILD_PREFIX: true

jobs:
