apiVersion: v1alpha
kind: cypress
defaults: {}
showconsolelog: false
sauce:
  region: us-west-1
  concurrency: 10
  sauceignore: .sauceignore
cypress:
  configFile: cypress.json
  version: 7.3.0
  record: false
  key: ""
suites:
- name: cypress - windows 10 - chrome smoke
  browser: chrome
  platformName: windows 10
  config:
    testFiles:
    - 'smoke/*.spec.*'
  mode: sauce
- name: cypress - windows 10 - chrome regression
  browser: chrome
  platformName: windows 10
  config:
    testFiles:
      ['regression/*.test.*']
  mode: sauce
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
