apiVersion: v1alpha
kind: cypress
showconsolelog: false
sauce:
  region: us-west-1
  tunnel: walkerlj0_tunnel_id
  metadata:
    name: Testing Cypress Support
    tags:
    - e2e
    - release team
    - other tag
    build: Release $CI_COMMIT_SHORT_SHA
  concurrency: 2
cypress:
  configFile: cypress.json
  version: 5.6.0
  record: false
  key: ""
suites:
- name: example test
  browser: chrome
  config:
    testFiles: ['**/example.test.js']

- name: login test
  browser: chrome
  platformName: "Windows 10"
  screenResolution: 2560x1600
  config:
    testFiles: ['**/login.spec.js']
docker:
  fileTransfer: mount
