apiVersion: v1alpha
kind: cypress
rootDir: ./
showconsolelog: false
sauce:
  region: us-west-1
  metadata:
    name: Testing Cypress Support
    tags:
    - e2e
    - release team
    - other tag
    build: Release $CI_COMMIT_SHORT_SHA
  concurrency: 10
cypress:
  configFile: cypress.json
  version: 5.6.0
  record: false
  key: ""
suites:
- name: example test
  browser: chrome
  config:
    testFiles: ['**/example.test.js']
- name: login test
  browser: chrome
  platformName: "Windows 10"
  screenResolution: 2560x1600
  config:
    testFiles: ['**/login.spec.js']

- name: Swag Labs Login Chrome
  browser: "chrome"
  platformName: "Windows 10"
  screenResolution: 1400x1050
  config:
    testFiles: [ "**/login.*" ]

- name: Swag Labs Login MicrosoftEdge
  browser: microsoftedge
  platformName: "Windows 10"
  screenResolution: 1400x1050
  config:
    testFiles: [ "**/login.*" ]

- name: "Swag Labs Login Firefox"
  browser: "firefox"
  platformName: "Windows 10"
  screenResolution: "1400x1050"
  config:
    testFiles: [ "**/login.*" ]
docker:
  fileTransfer: mount
